-- ---------------------------------------------------------
-- TB_AGENDAMENTO_REDUCAO_CARBONO
-- ---------------------------------------------------------
CREATE TABLE TB_AGENDAMENTO_REDUCAO_CARBONO (
    ID_AGENDAMENTO      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    ID_EMPRESA          NUMBER(19)      NOT NULL,
    DS_TITULO           VARCHAR2(150)   NOT NULL,
    DS_DESCRICAO        VARCHAR2(500)   NOT NULL,
    DS_TIPO_INICIATIVA  VARCHAR2(50)    NOT NULL,
    VL_META_CO2         NUMBER(15,4)    NOT NULL,
    DT_INICIO           DATE            NOT NULL,
    DT_FIM              DATE            NOT NULL,
    DS_STATUS           VARCHAR2(20)    DEFAULT 'PENDENTE' NOT NULL,
    DT_CRIACAO          TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AGENDAMENTO PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_AGENDAMENTO_EMPRESA FOREIGN KEY (ID_EMPRESA)
        REFERENCES TB_EMPRESA (ID_EMPRESA),
    CONSTRAINT CK_AGENDAMENTO_STATUS CHECK (DS_STATUS IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT CK_AGENDAMENTO_DATAS CHECK (DT_FIM > DT_INICIO)
);

CREATE INDEX IX_AGENDAMENTO_EMPRESA ON TB_AGENDAMENTO_REDUCAO_CARBONO (ID_EMPRESA);
CREATE INDEX IX_AGENDAMENTO_STATUS  ON TB_AGENDAMENTO_REDUCAO_CARBONO (DS_STATUS);

-- ---------------------------------------------------------
-- Dados iniciais de agendamento
-- ---------------------------------------------------------
INSERT INTO TB_AGENDAMENTO_REDUCAO_CARBONO
    (ID_EMPRESA, DS_TITULO, DS_DESCRICAO, DS_TIPO_INICIATIVA, VL_META_CO2, DT_INICIO, DT_FIM, DS_STATUS)
VALUES (1, 'Troca de Caldeiras por Biomassa',
        'Substituicao gradual das caldeiras a gas por caldeiras de biomassa certificada para reducao de emissoes',
        'Eficiencia Energetica', 600.0000, DATE '2025-07-01', DATE '2026-06-30', 'PENDENTE');

INSERT INTO TB_AGENDAMENTO_REDUCAO_CARBONO
    (ID_EMPRESA, DS_TITULO, DS_DESCRICAO, DS_TIPO_INICIATIVA, VL_META_CO2, DT_INICIO, DT_FIM, DS_STATUS)
VALUES (2, 'Instalacao de Paineis Solares',
        'Instalacao de 500 kWp de energia solar fotovoltaica nas unidades industriais',
        'Energia Renovavel', 200.0000, DATE '2025-06-01', DATE '2025-12-31', 'EM_ANDAMENTO');

INSERT INTO TB_AGENDAMENTO_REDUCAO_CARBONO
    (ID_EMPRESA, DS_TITULO, DS_DESCRICAO, DS_TIPO_INICIATIVA, VL_META_CO2, DT_INICIO, DT_FIM, DS_STATUS)
VALUES (3, 'Eletrificacao da Frota de Entregas',
        'Substituicao de 50% dos veiculos de entrega por modelos eletricos ate dezembro de 2026',
        'Eletrificacao de Frota', 1800.0000, DATE '2025-08-01', DATE '2026-12-31', 'PENDENTE');

COMMIT;
